openapi: 3.0.1
info:
  title: Order API
  description: Sample Order API
  version: '5.0'
  contact:
    email: devs@specmatic.io
servers:
  - url: "http://localhost:3000"
tags:
  - name: Product
    description: Product Related APIs
  - name: Order
    description: Order Related APIs
paths:
  "/products/{id}":
    parameters:
      - name: id
        schema:
          type: number
        in: path
        required: true
        examples:
          GET_PRODUCT:
            value: 10
          UPDATE_PRODUCT:
            value: 10
          DELETE_PRODUCT:
            value: 20
          INVALID_ID:
            value: "344"
    get:
      description: Fetch product details
      operationId: get-products-id
      tags:
      - Product
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/Product"
              examples:
                GET_PRODUCT:
                  value:
                    name: "XYZ Phone"
                    type: "gadget"
                    inventory: 10
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Not found"
    post:
      description: Update product details
      operationId: post-products-id
      tags:
      - Product
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Update successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_PRODUCT:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/ProductDetails"
            examples:
              UPDATE_PRODUCT:
                value:
                  name: "XYZ Fone"
                  type: "gadget"
                  inventory: 10
    delete:
      description: Delete a product
      tags:
      - Product
      operationId: delete-products-id
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Deletion successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_PRODUCT:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
  "/products/{id}/image":
    put:
      description: Update or upload a product image
      operationId: updateProductImage
      tags:
      - Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          examples:
            UPDATE_IMAGE:
              value: 10
      requestBody:
        description: Image file to be associated with the product
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
                  description: The image file to upload
            encoding:
              image:
                contentType: image/png, image/jpeg
            examples:
              UPDATE_IMAGE:
                value:
                  image:
                    externalValue: ".specmatic/repos/specmatic-order-contracts/io/specmatic/examples/store/openapi/box_image.jpg"
      responses:
        "200":
          description: Product image updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  productId:
                    type: integer
              examples:
                UPDATE_IMAGE:
                  value:
                    message: "Product image updated successfully"
                    productId: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
  /products:
    get:
      description: GET Products based on type
      operationId: get-products
      tags:
      - Product
      parameters:
        - name: type
          in: query
          schema:
            $ref: "./common.yaml#/components/schemas/ProductType"
      responses:
        "200":
          description: List of products in the response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "common.yaml#/components/schemas/Product"
    post:
      description: POST products
      operationId: post-products
      tags:
      - Product
      security:
        - ApiKeyAuth: []
      parameters:
        - name: Idempotency-Key
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/IdempotencyKey"
          examples:
            CREATE_PRODUCT:
                value: (uuid)
      requestBody:
        content:
          application/json:
            schema:
              $ref: "common.yaml#/components/schemas/ProductDetails"
            examples:
                CREATE_PRODUCT:
                  value:
                    name: "XYZ Phone"
                    type: "gadget"
                    inventory: 10
      responses:
        "201":
          description: POST /products
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/ProductId"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
  /orders:
    post:
      description: POST /orders
      operationId: post-orders
      tags:
      - Order
      security:
        - ApiKeyAuth: []
      parameters:
        - name: Idempotency-Key
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/IdempotencyKey"
          examples:
            CREATE_ORDER:
                value: (uuid)
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderDetails"
            examples:
              CREATE_ORDER:
                value:
                  productid: 10
                  count: 2
      responses:
        "201":
          description: POST /orders
          content:
            application/json:
              schema:
                $ref: "common.yaml#/components/schemas/OrderId"
              examples:
                CREATE_ORDER:
                  value:
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
    get:
      description: Search for orders
      operationId: get-orders
      tags:
      - Order
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./common.yaml#/components/schemas/Order"
              examples:
                200_OK:
                  value:
                    - productid: 10
                      count: 2
                      status: "pending"
                      id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      parameters:
        - name: productid
          in: query
          schema:
            type: number
          examples:
            200_OK:
              value: 10
        - name: status
          in: query
          schema:
            type: string
          examples:
            200_OK:
              value: fulfilled
  /orders/bulk:
    post:
      description: Create multiple orders in bulk
      operationId: post-orders-bulk
      tags:
      - Order
      security:
        - ApiKeyAuth: []
      parameters:
        - name: Idempotency-Key
          in: header
          required: true
          schema:
            $ref: "#/components/schemas/IdempotencyKey"
          examples:
            BULK_CREATE_ORDERS:
                value: (uuid)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/OrderDetails"
            examples:
              BULK_CREATE_ORDERS:
                value:
                  - productid: 10
                    count: 1
                  - productid: 30
                    count: 2
      responses:
        "200":
          description: Orders created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "common.yaml#/components/schemas/OrderId"
              examples:
                BULK_CREATE_ORDERS:
                  value:
                    - id: 10
                    - id: 30
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
  "/orders/{id}":
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        examples:
          GET_ORDER:
            value: 10
          UPDATE_ORDER:
            value: 10
          DELETE_ORDER:
            value: 20
          INVALID_ID:
            value: 433
    get:
      description: Fetch order details
      operationId: get-orders-id
      tags:
      - Order
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/Order"
              examples:
                GET_ORDER:
                  value:
                    productid: 10
                    count: 2
                    status: "pending"
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Product with id 344 was not found"
    post:
      description: Update order details
      operationId: post-orders-id
      tags:
      - Order
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_ORDER:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderUpdate"
            examples:
              UPDATE_ORDER:
                value:
                  productid: 10
                  count: 1
                  status: pending
    delete:
      description: Cancel an order
      operationId: delete-orders-id
      tags:
      - Order
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Cancel successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_ORDER:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
components:
  schemas:
    OrderDetails:
      title: Order Details
      type: object
      properties:
        productid:
          type: integer
        count:
          type: integer
      required:
        - productid
        - count

    OrderUpdate:
      allOf:
        - $ref: '#/components/schemas/OrderDetails'
        - type: object
          properties:
            status:
              $ref: './common.yaml#/components/schemas/OrderStatus'

    IdempotencyKey:
      type: string
      format: uuid

    ErrorResponseBody:
      properties:
        id:
          type: number
        timestamp:
          type: string
        status:
          type: number
        error:
          type: string
        message:
          type: string

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authenticate
