name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check API Contracts
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Save Specmatic license
        run: |
          mkdir -p ~/.specmatic
          echo "${{ secrets.SPECMATIC_LICENSE_KEY }}" > ~/.specmatic/specmatic-license.txt

      - name: Run backward compatibility check
        run: |
          docker run -v "$(pwd):/usr/src/app" \
            -v ~/.specmatic:/root/.specmatic:ro \
            -e GIT_CONFIG_COUNT=1 \
            -e GIT_CONFIG_KEY_0=safe.directory \
            -e GIT_CONFIG_VALUE_0='*' \
            specmatic/enterprise \
            backward-compatibility-check --base-branch=origin/main

      - name: Upload backward compatibility CTRF report
        uses: actions/upload-artifact@v6
        if: always() # Run even if the backward compatibility check fails
        with:
          name: backward-compatibility-ctrf-report
          path: build/reports/specmatic/backward_compatibility/ctrf/*.json

      - name: Render backward compatibility CTRF report
        uses: ctrf-io/github-test-reporter@v1
        if: always() # Run even if the backward compatibility check fails
        with:
          report-path: build/reports/specmatic/backward_compatibility/ctrf/*.json
